CLI prototype almost done
19chonm/461_1_23 pull request #15
Opened 2023-01-25 21:16 UTC by emilejbm

build, install, test, URL_FILE commands are recognized. URL_FILE takes in txt file and prints content within file. Not sure what to install for install command. Missing the test suite to test on.

2023-01-27 19:59 UTC, Ashassins commented
Resolves Issue #9

2023-01-27 20:03 UTC, Ashassins requested changes

2023-01-27 20:03 UTC, Ashassins commented on commands/CLI/test.go
> +var testCmd = &cobra.Command{
I would change the filename. Maybe start organizing the test suite folder and structure?

2023-01-27 20:03 UTC, Ashassins commented on commands/CLI/url_file.go
> +var urlfileCmd = &cobra.Command{
please add some comments on how you expect url_file links to API, etc.

2023-01-27 20:03 UTC, Ashassins commented on functionality/CLI/team23.go
> +    if err != nil {
Can we throw an error instead?

2023-02-01 00:54 UTC, benschwartz9 commented
Merged through https://github.com/19chonm/461_1_23/pull/19

2023-02-01 00:54 UTC, closed without merging